[package]
name = "lemmy-data-exporter"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.26"
influxdb = { version = "0.6", features = ["derive"] }
tokio-postgres = "0.7.8"

tokio = { version = "1.21.2", features = [ "macros", "rt-multi-thread" ] }
