FROM rust:1.73-bullseye AS builder

WORKDIR /app-src

COPY Cargo.lock ./Cargo.lock
COPY Cargo.toml ./Cargo.toml
COPY src        ./src

RUN [ "cargo", "build", "--release" ]

FROM debian:bullseye-slim
# You can try to change the above image name, but you'll need to ensure that whichever
# image you use has the proper libraries to support running the binaries generated by Rust

COPY --from=builder /app-src/target/release/lemmy-data-exporter /bin/lemmy-data-exporter

CMD [ "/bin/lemmy-data-exporter" ]
